### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by jbaginski** [mrmike/Ok2Curl#15]
I'm not able to sync gradle.
> Error:Dependency com.github.mrmike:ok2curl:0.2.0 on project app resolves to an APK archive which is not supported as a compilation dependency.

**Comment by mrmike** [comment]
Hi,

Please use latest `0.2.2` version or the snapshot version which will be always up-to-date.

```
compile 'com.github.mrmike:ok2curl:0.2.2'
```
or
```
compile 'com.github.mrmike:ok2curl:master-SNAPSHOT'
```

Thanks for reporting issue :)

**Comment by jbaginski** [comment]
perfect, thanks for the quick response :)
