### ISSUE TITLE
Publish source artifacts to jitpack.io

### ISSUE THREAD

**Issue by yschimke** [mrmike/Ok2Curl#17]
Doesn't seem to be available at the moment.  Publishing would be helpful when using ok2curl as a library and debugging.

https://jitpack.io/com/github/mrmike/ok2curl/0.2.2/ok2curl-0.2.2-sources.jar

Nice library BTW

**Comment by mrmike** [comment]
Hi @yschimke 

Thanks for the info. I've added task for generating jar with sources in the latest PR. You can check version `0.2.3` https://jitpack.io/com/github/mrmike/ok2curl/0.2.3/

**Comment by yschimke** [comment]
Worked with a simple version bump.  Thanks.
