### ISSUE TITLE
Library not available in Maven Central

### ISSUE THREAD

**Issue by mgawinec** [mrmike/Ok2Curl#24]
How can I use your library with maven?

I tried to get it from Maven Central repo:

```xml
        <dependency>
            <groupId>com.github.mrmike</groupId>
            <artifactId>okcurl</artifactId>
            <version>0.2.5</version>
        </dependency>
```

but there's no such groupId. Going to https://repo.maven.apache.org/maven2/com/github/mrmike/ returns 404.

**Comment by jacek-marchwicki** [comment]
@mgawinec library is not available through mavenCentral it on jitpack repository

you need to use their repository:

```xml
<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

**Comment by mgawinec** [comment]
@jacek-marchwicki  Thanks for prompt response.

It looks like access to this repo is protected:
```
 Could not transfer artifact com.github.mrmike:okcurl:pom:0.2.5 from/to jitpack.io (https://jitpack.io): Not authorized , ReasonPhrase:Repo not found or no access token provided. 
```
What user/password do I need to provide?

**Comment by mgawinec** [comment]
My bad, artifact should be ok2curl, not okcurl

  <dependency>
            <groupId>com.github.mrmike</groupId>
            <artifactId>ok2curl</artifactId>
            <version>0.2.5</version>
        </dependency>
