### ISSUE TITLE
Recognize Basic Authorization

### ISSUE THREAD

**Issue by mgawinec** [mrmike/Ok2Curl#28]
In case request contains Authorization header of Basic type, e.g.,
```
Authorizaton: Basic bWFjaWVrOnRham5laGFzbG8xMjM=
```
would it be possible to have the following
```
curl -u maciej:tajnehaslo123 ...
```
?

**Comment by mrmike** [comment]
Hi @mgawinec 

I think I can add this feature in the next version. Thanks for the suggestion :)

**Comment by mrmike** [comment]
Hi @mgawinec 

There's a support for HeaderModifiers in the latest version. You can read more here: https://github.com/mrmike/Ok2Curl#header-modifiers

Simply you have to create HeaderModifier and add it to `CurlInterceptor`. I've added sample [Header](https://github.com/mrmike/Ok2Curl/blob/master/sample/src/main/java/com/moczul/sample/modifier/BasicAuthorizationHeaderModifier.java) that is decoding basic Auth header. So you can copy it and use it in your project.

If you have any questions just let me know.

**Comment by dzieciou** [comment]
Thanks. Unfortunately, this is solution just transforms one header into another, e.g.
```
Authorization: bWFjaWVqOnNlY3JldA==
```
will be transformed into
```
Authorization: maciej:secret`

While I was expecting something that will transform an original header into curl command parameter, e.g.:
```
-u maciej:secret
```

**Comment by mrmike** [comment]
Hi @mgawinec 

Sure I will try to add it as well. I hope this solution will work for you for a while.
