### ISSUE TITLE
Any chance to get it into Maven Central?

### ISSUE THREAD

**Issue by dzieciou** [mrmike/Ok2Curl#31]
Our corporate policy accept artifacts from Maven Central only.

Would there be a chance to have this artifact in Maven Central repo as well?

**Comment by mrmike** [comment]
Hi @dzieciou 

Does `JCenter` also work for you?

**Comment by Hazer** [comment]
@mrmike I don't know for him, but for me `JCenter ` works. And if I am not wrong, Bintray allows you to publish to `Maven Central` "automagically" when you publish to `JCenter`.

**Comment by mrmike** [comment]
Hi @dzieciou and @Hazer 
I'm still [working on that](https://github.com/mrmike/Ok2Curl/pull/36) but latest version `0.4.1` is available on JCenter(). 

Just add `jcenter()` to your repository and add 
```
implementation 'com.github.mrmike:ok2curl:0.4.1'
```

**Comment by sureshg** [comment]
I know this issue is closed, but can you reconsider the plan to publish to maven central? Our company uses a nexus proxy which can basically pull only from maven central. Getting approval for a new repo (like jcenter) is tedious.

**Comment by mrmike** [comment]
hi @sureshg 

I've created an issue for doing that: https://github.com/mrmike/Ok2Curl/issues/47
