### ISSUE TITLE
Add library to Maven Central

### ISSUE THREAD

**Issue by mrmike** [mrmike/Ok2Curl#47]
* Make library available on maven central

**Comment by sureshg** [comment]
@mrmike I hate to ask this, still any update on this?

**Comment by mrmike** [comment]
Hi @sureshg 

I've decided to not support maven-central. If you are not able to use `jcenter()` please use jar from https://bintray.com/moczul/maven/ok2curl/0.4.5#files/com%2Fgithub%2Fmrmike%2Fok2curl%2F0.4.5

Thanks
