### ISSUE TITLE
Migrate from JCenter to MavenCentral

### ISSUE THREAD

**Issue by JcMinarro** [mrmike/Ok2Curl#60]
[JFrog announced](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) yesterday that Bintray and JCenter repositories will be closed by May 1st.
You use JCenter to distribute your artifacts. 
Are you planning to migrate to MavenCentral?

**Comment by mrmike** [comment]
Hi @JcMinarro,

Thanks for reporting that. I'll try to upload this library to Maven Central 🤞

**Comment by JcMinarro** [comment]
We have written [some guides](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) about how to publish to Maven Central, Hope it will help you ;)

**Comment by mrmike** [comment]
Hi @JcMinarro,

The latest version `0.7.0` is published to Maven Central - https://repo1.maven.org/maven2/com/github/mrmike/ok2curl/
